/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SybelInternalTokens } from "./SybelInternalTokens";
export type { SybelToken } from "./SybelToken";
