/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as badges from "./badges";
export type { badges };
import type * as minter from "./minter";
export type { minter };
import type * as reward from "./reward";
export type { reward };
import type * as tokens from "./tokens";
export type { tokens };
import type * as utils from "./utils";
export type { utils };
import type * as wallets from "./wallets";
export type { wallets };
