/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IListenerBadges,
  IListenerBadgesInterface,
} from "../../../../contracts/badges/payment/IListenerBadges";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_listener",
        type: "address",
      },
    ],
    name: "getBadge",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_listener",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "_badge",
        type: "uint64",
      },
    ],
    name: "updateBadge",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IListenerBadges__factory {
  static readonly abi = _abi;
  static createInterface(): IListenerBadgesInterface {
    return new utils.Interface(_abi) as IListenerBadgesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IListenerBadges {
    return new Contract(address, _abi, signerOrProvider) as IListenerBadges;
  }
}
