/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPodcastBadges,
  IPodcastBadgesInterface,
} from "../../../../contracts/badges/payment/IPodcastBadges";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_podcastId",
        type: "uint256",
      },
    ],
    name: "getBadge",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_podcastId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_badge",
        type: "uint256",
      },
    ],
    name: "updateBadge",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPodcastBadges__factory {
  static readonly abi = _abi;
  static createInterface(): IPodcastBadgesInterface {
    return new utils.Interface(_abi) as IPodcastBadgesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPodcastBadges {
    return new Contract(address, _abi, signerOrProvider) as IPodcastBadges;
  }
}
