[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
cache_path = 'forge-cache'
# extra_output = ["ir", "irOptimized"]
# extra_output = ["irOptimized"]

# Remove bytecode hash at the end of compiled bytecode
bytecode_hash = "none"

# Allow read/write permission on current path
fs_permissions = [{ access = "read-write", path = "./" }]

# For OZ upgrades checks
build_info = true
extra_output = ["storageLayout"]

# Optimizer config
optimizer = true
optimizer_runs = 100_000
via-ir = false

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

# Fuzzing config
[fuzz]
runs = 1000
include_storage = true
include_push_bytes = true

# CI config
[profile.ci]
  fuzz = { runs = 10_000, seed = '0xacab' }
  verbosity = 4

# Invariant config
[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

[etherscan]
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  goerli = { key = "${API_KEY_ETHERSCAN}", url = "https://api-goerli.etherscan.io/api" }
  polygon = { key = "${API_KEY_POLYGONSCAN}", url = "https://api.polygonscan.com/api" }
  mumbai = { key = "${API_KEY_POLYGONSCAN}", url = "https://api-testnet.polygonscan.com/api" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  localhost = "http://localhost:8545"
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY_MAINNET}"
  goerli = "https://eth-goerli.g.alchemy.com/v2/${API_KEY_ALCHEMY_GOERLI}"
  polygon = "https://polygon-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY_POLYGON}" 
  mumbai = "https://polygon-mumbai.g.alchemy.com/v2/${API_KEY_ALCHEMY_MUMBAI}"
