[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'forge-cache'
# extra_output = ["ir", "irOptimized"]
# extra_output = ["irOptimized"]

# For OZ upgrades checks
build_info = true
extra_output = ["storageLayout"]

# Optimizer config
optimizer = true
optimizer_runs = 100_000
via-ir = true

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

# Fuzzing config
[fuzz]
runs = 2048
max_test_rejects = 65536
seed = '0xacab'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Invariant config
[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config