/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface PaymentBadgesAccessorInterface extends utils.Interface {
  functions: {
    "listenerBadges()": FunctionFragment;
    "podcastBadges()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "listenerBadges" | "podcastBadges"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "listenerBadges",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "podcastBadges",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "listenerBadges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "podcastBadges",
    data: BytesLike
  ): Result;

  events: {
    "Initialized(uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
}

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface PaymentBadgesAccessor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PaymentBadgesAccessorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    listenerBadges(overrides?: CallOverrides): Promise<[string]>;

    podcastBadges(overrides?: CallOverrides): Promise<[string]>;
  };

  listenerBadges(overrides?: CallOverrides): Promise<string>;

  podcastBadges(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    listenerBadges(overrides?: CallOverrides): Promise<string>;

    podcastBadges(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;
  };

  estimateGas: {
    listenerBadges(overrides?: CallOverrides): Promise<BigNumber>;

    podcastBadges(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    listenerBadges(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    podcastBadges(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
