/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRewarder,
  IRewarderInterface,
} from "../../../contracts/reward/IRewarder";

const _abi = [
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_listener",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "_podcastIds",
        type: "uint256[]",
      },
      {
        internalType: "uint16[]",
        name: "_listenCounts",
        type: "uint16[]",
      },
    ],
    name: "payUser",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRewarder__factory {
  static readonly abi = _abi;
  static createInterface(): IRewarderInterface {
    return new utils.Interface(_abi) as IRewarderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRewarder {
    return new Contract(address, _abi, signerOrProvider) as IRewarder;
  }
}
