/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ContentPool } from "./ContentPool";
export type { ContentPoolReview } from "./ContentPoolReview";
