/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FoundationWallet__factory } from "./FoundationWallet__factory";
export { VestingWallets__factory } from "./VestingWallets__factory";
