/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FractionCostBadges } from "./FractionCostBadges";
export type { IFractionCostBadges } from "./IFractionCostBadges";
