/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FoundationWallet } from "./FoundationWallet";
export type { VestingWallets } from "./VestingWallets";
