/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IListenerBadges } from "./IListenerBadges";
export type { IPodcastBadges } from "./IPodcastBadges";
export type { ListenerBadges } from "./ListenerBadges";
export type { PodcastBadges } from "./PodcastBadges";
