/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  PaymentBadgesAccessor,
  PaymentBadgesAccessorInterface,
} from "../../../../contracts/badges/access/PaymentBadgesAccessor";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [],
    name: "listenerBadges",
    outputs: [
      {
        internalType: "contract IListenerBadges",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "podcastBadges",
    outputs: [
      {
        internalType: "contract IPodcastBadges",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class PaymentBadgesAccessor__factory {
  static readonly abi = _abi;
  static createInterface(): PaymentBadgesAccessorInterface {
    return new utils.Interface(_abi) as PaymentBadgesAccessorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PaymentBadgesAccessor {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as PaymentBadgesAccessor;
  }
}
