/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFractionCostBadges,
  IFractionCostBadgesInterface,
} from "../../../../contracts/badges/cost/IFractionCostBadges";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_fractionId",
        type: "uint256",
      },
    ],
    name: "getBadge",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_fractionId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_coefficient",
        type: "uint256",
      },
    ],
    name: "updateBadge",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFractionCostBadges__factory {
  static readonly abi = _abi;
  static createInterface(): IFractionCostBadgesInterface {
    return new utils.Interface(_abi) as IFractionCostBadgesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFractionCostBadges {
    return new Contract(address, _abi, signerOrProvider) as IFractionCostBadges;
  }
}
