/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FractionCostBadges__factory } from "./FractionCostBadges__factory";
export { IFractionCostBadges__factory } from "./IFractionCostBadges__factory";
